language: cpp

sudo: required

env:
  global:
    - HXCPP_COMPILE_CACHE=~/hxcache

matrix:
  include:
    - os: linux
      dist: trusty
      install:
        - bash tools/haxe/build_linux.sh
        - travis_retry sudo apt-get install gcc-multilib g++-multilib -y;
    - os: osx
      osx_image: xcode8.3
      install:
        - bash tools/haxe/build_osx.sh;

script:
  - cd ${TRAVIS_BUILD_DIR}/tools/run
  - haxe compile.hxml
  - cd ${TRAVIS_BUILD_DIR}/tools/hxcpp
  - haxe compile.hxml
  - cd ${TRAVIS_BUILD_DIR}/project
  - haxe compile-cppia.hxml
  - cd ${TRAVIS_BUILD_DIR}/test
  - haxe --run RunTests cffi
  - haxe --run RunTests haxe
  - haxe --run RunTests telemetry
  - haxe --run RunTests std32
  - haxe --run RunTests std64
  - haxe --run RunTests debugger
  - haxe --run RunTests native
  - cd ~/haxe/tests/unit
  - haxe compile-cpp.hxml -D HXCPP_M32 && ./bin/cpp/TestMain-debug && rm -rf bin/cpp
  - haxe compile-cpp.hxml -D HXCPP_M64 && ./bin/cpp/TestMain-debug
  - haxe compile-cppia.hxml -debug && haxelib run hxcpp ./bin/unit.cppia
