version: "{build}"

clone_folder: C:\projects\hxcpp

environment:
    global:
        HAXE_ROOT: C:\projects\haxe
        HAXELIB_ROOT: C:\projects\haxelib
        CYG_ROOT: C:\cygwin
        ADD_REVISION: 1
        OCAMLOPT: ocamlopt.opt
        HAXEPATH: "%APPVEYOR_BUILD_FOLDER%"
    matrix:
        - HXCPP_ARCH: "32"
        - HXCPP_ARCH: "64"

cache:
    - opam32.tar.xz -> appveyor.yml

install:
    - '%CYG_ROOT%/bin/bash -lc "echo initialize"'
    # Install ocaml
    - curl -fsS -o cygwin-setup.exe --retry 3 https://cygwin.com/setup-x86.exe
    - 'cygwin-setup.exe -g -q -R "%CYG_ROOT%" -P make -P git -P mingw64-i686-zlib -P rsync -P patch -P diffutils -P curl -P unzip -P m4 -P perl -P mingw64-i686-gcc-core -P mingw64-i686-pcre'
    - if not exist "opam32.tar.xz" (
        curl -fsS -o opam32.tar.xz --retry 3 https://dl.dropboxusercontent.com/s/eo4igttab8ipyle/opam32.tar.xz
      )
    - 7z x "opam32.tar.xz" -so | 7z x -aoa -si -ttar
    - '%CYG_ROOT%/bin/bash -lc "cd \"$OLDPWD\" && bash opam32/install.sh"'
    - '%CYG_ROOT%/bin/bash -lc "opam init mingw \"https://github.com/fdopen/opam-repository-mingw.git\" --comp 4.02.3+mingw32c --switch 4.02.3+mingw32c --auto-setup --yes"'
    - '%CYG_ROOT%/bin/bash -lc "opam install camlp4 --yes"'
    # Install neko. Just download the chocolatey package instead of building from source in order to save time...
    - cinst neko -y
    - RefreshEnv
    - neko -version
    # expose the dll files
    - set "PATH=%PATH%;%CYG_ROOT%/usr/i686-w64-mingw32/sys-root/mingw/bin"
    # Install haxe
    - git clone --recursive --depth 1 -q https://github.com/HaxeFoundation/haxe.git %HAXE_ROOT%
    - 'cd %HAXE_ROOT%'
    - 'set PATH=%PATH%;%HAXE_ROOT%'
    - '%CYG_ROOT%\bin\bash -lc "cd \"$OLDPWD\" && make -s -f Makefile.win"'
    - haxe -version
    - cd %APPVEYOR_BUILD_FOLDER%
    - mkdir "%HAXELIB_ROOT%"
    - haxelib setup "%HAXELIB_ROOT%"
    - haxelib install record-macros

build_script:
    - haxelib dev hxcpp %APPVEYOR_BUILD_FOLDER%
    - cd %APPVEYOR_BUILD_FOLDER%\tools\run
    - haxe compile.hxml
    - cd %APPVEYOR_BUILD_FOLDER%\tools\hxcpp
    - haxe compile.hxml

test_script:
    - cd %APPVEYOR_BUILD_FOLDER%\test\std
    - haxe compile%HXCPP_ARCH%.hxml && .\cpp%HXCPP_ARCH%\Test
    - cd %APPVEYOR_BUILD_FOLDER%\test\haxe
    - haxe compile.hxml -debug -D HXCPP_M%HXCPP_ARCH% && .\bin\TestMain-debug
    # tests from haxe repo
    - cd %HAXE_ROOT%\tests\unit
    - haxe compile-cpp.hxml -D HXCPP_M%HXCPP_ARCH% && .\bin\cpp\TestMain-debug
